// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWYTjYCLyFVpHxabmAvw9lq5u36qn4UA',
    appId: '1:963867515310:web:a2ec92e73c751b9de7903f',
    messagingSenderId: '963867515310',
    projectId: 'onebody-cddc4',
    authDomain: 'onebody-cddc4.firebaseapp.com',
    storageBucket: 'onebody-cddc4.appspot.com',
    measurementId: 'G-H851DCBP1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACM9sE6d7_Vacer9bHU6wr28mvwgfzsVg',
    appId: '1:963867515310:android:cea0656a305c2c00e7903f',
    messagingSenderId: '963867515310',
    projectId: 'onebody-cddc4',
    storageBucket: 'onebody-cddc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKfnrZh5jSIlPCPZEmRPLUStGhkq7G7xA',
    appId: '1:963867515310:ios:dbae42acd24d77dce7903f',
    messagingSenderId: '963867515310',
    projectId: 'onebody-cddc4',
    storageBucket: 'onebody-cddc4.appspot.com',
    iosClientId: '963867515310-rijkgomo28g5eal8e9i84vmioig94dcf.apps.googleusercontent.com',
    iosBundleId: 'com.project.onebody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKfnrZh5jSIlPCPZEmRPLUStGhkq7G7xA',
    appId: '1:963867515310:ios:dbae42acd24d77dce7903f',
    messagingSenderId: '963867515310',
    projectId: 'onebody-cddc4',
    storageBucket: 'onebody-cddc4.appspot.com',
    iosClientId: '963867515310-rijkgomo28g5eal8e9i84vmioig94dcf.apps.googleusercontent.com',
    iosBundleId: 'com.project.onebody',
  );
}
